### ISSUE TITLE
Binary Labeling Issue in Perceptron Model

### ISSUE THREAD

**Issue by MathieuSrour** [rafaelgreca/scratchml#19]
The Perceptron model currently assumes that labels are already in a binary format of 0 and 1. However, if labels are provided in a different binary format, such as -1 and 1 (common in many datasets), the model raises an error or behaves unexpectedly.

A suggested solution would be to map any binary labels to 0 and 1 before training the Perceptron model. This adjustment can be made in the perceptron.py script within the models directory, in the following part of the code:

if len(self.classes_) == 2:
    # Map the unique classes to 0 and 1
    y = np.where(y == self.classes_[0], 0, 1)

**Comment by rafaelgreca** [comment]
Hey @MathieuSrour, can you provide me some examples so I can reproduce the error and see what is happening? I'm going to work on that.

**Comment by rafaelgreca** [comment]
Fixed in version 10.0.0! Thanks for your contribution!
